services:
  kan:
    image: ghcr.io/kanbn/kan:latest
    container_name: kan
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT}:3000
    depends_on:
      - kan-db
  kan-db:
    image: postgres:15
    container_name: kan-db
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: null

