services:
  postgres:
    image: postgres
    container_name: kaneo-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  api:
    image: ghcr.io/usekaneo/api:latest
    container_name: kaneo-api
    restart: unless-stopped
    ports:
      - "1337:1337"
    env_file:
      - .env

  web:
    image: ghcr.io/usekaneo/web:latest
    container_name: kaneo
    restart: unless-stopped
    ports:
      - "${PORT}:5173"
    env_file:
      - .env

volumes:
  data:
